project_id = "sentinelone-428814"
dataset_id = "sentinelone"
tmp_sentinelone_issues_table = "tmp_sentinelone_issues"
sentinelone_issues_table = "sentinelone_issues"
schedule_tmp = "every 12 hours from 00:10 to 00:00"
schedule_upsert = "every 12 hours from 00:15 to 00:00"
